# Custom Language File for Launcher Customizer

[ejs.app]
title = "Epicraft Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Crabe-Corp/Epicraft-Launcher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/HWJnZ9UmAf"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Epicraft !"
welcomeDescription = "Le serveur fait par des étudiants pour des étudiants."
welcomeDescCTA = "Rejoignez-nous sur Discord pour plus d'informations !"
